# Generated by Django 6.0.3 on 2026-04-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(default='/', max_length=200)),
                ('is_logged_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
