services:
  - type: web
    name: glow-cart
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear && python manage.py migrate --noinput && python manage.py create_admin
    startCommand: gunicorn mysite.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --preload
    envVars:
      - key: DATABASE_URL
        value: postgresql://glowcart_db_user:G9Foib9SfAJtVvhQy9f6Vqx04rMN6iRq@dpg-d7c0c2l8nd3s73fiiih0-a/glowcart_db
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_HOST_USER
        value: glowcart0811@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: qlgraavwgxxbgyfd
      - key: ADMIN_USERNAME
        value: MonitJain
      - key: ADMIN_EMAIL
        value: glowcart0811@gmail.com
      - key: ADMIN_PASSWORD
        value: monitkagot@0811
      - key: CLOUDINARY_URL
        value: cloudinary://811982224118176:-y5wv_64ms--L5PnsKxsdrlmafE@dkla4wg06
